This is makeindex, version 2.15 [TeX Live 2012] (kpathsea + Thai support).
Scanning style file ./monRapport.ist...........................done (27 attributes redefined, 0 ignored).
Scanning input file monRapport.acn....done (43 entries accepted, 0 rejected).
Sorting entries....done (257 comparisons).
Generating output file monRapport.acr....done (47 lines written, 0 warnings).
Output written in monRapport.acr.
Transcript written in monRapport.alg.
